# Generated by Django 4.1 on 2022-08-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_terms', models.CharField(max_length=100)),
                ('min_pensum', models.IntegerField()),
                ('max_pensum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image_base64', models.CharField(max_length=99999)),
            ],
        ),
        migrations.CreateModel(
            name='JobScout24Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=50)),
                ('origin_company', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('_attributes', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('l', 'liked'), ('d', 'disliked'), ('u', 'unknown')], default='u', max_length=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tindershow.source')),
            ],
        ),
    ]
