version: '3.8'

services:
  web:
    build: .
    command: gunicorn floxesNewJob.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app
      - ./staticfiles:/home/app/web/staticfiles
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env.prod